// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/background.js"
    | "/content-scripts/content.js"
    | "/devtools-panel.html"
    | "/devtools.html"
    | "/icon/128-restricted.png"
    | "/icon/128.png"
    | "/icon/16-restricted.png"
    | "/icon/16.png"
    | "/icon/32-restricted.png"
    | "/icon/32.png"
    | "/icon/48-restricted.png"
    | "/icon/48.png"
    | "/icon/logo.svg"
    | "/icon/logo_square.png"
    | "/injected.js"
    | "/inspect.svg"
    | "/lexical.svg"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
