[book]
title = "Indexed Centralized Docs"
authors = ["KlikneteZde.Cz and GroupWare.Cz"]
language = "en"
multilingual = false
src = "src"
description = "EasyITcenter & EasySYSTEMbuilder Groupware Solution Projects Documentation"

[rust]
edition = "2021"

[preprocessor.index]

[preprocessor.links]


[output.html.search]
enable = true  
limit-results = 50
teaser-word-count = 50
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[output.html]
theme = "rust"
mathjax-support = true
git-repository-url = "https://groupware.cz:5000/Home/Public"
default-theme = "rust"
additional-css = ["./css/global.css"]
additional-js = ["./js/jquery-3.6.0.min.js","./js/mermaid.min.cdn.js","./js/jquery-storage.js","./js/autotranslate.js","./js/globalscript.js"]
sidebar-header-nav = true
admonitions = true
smart-punctuation = true
definition-lists = true

[output.html.playground]
editable = false
copyable = true
copy-js = true 
line-numbers = true 
runnable = true 

[output.html.print]
enable = true 
page-break = true

[output.html.fold]
enable = false
level = 0
