USE [master]
GO
/****** Object:  Database [EICwebHosting]    Script Date: 30.08.2024 3:10:48 ******/
CREATE DATABASE [EICwebHosting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EICwebHosting', FILENAME = N'C:\Database\EICwebHosting.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EICwebHosting_log', FILENAME = N'C:\Database\EICwebHosting.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [EICwebHosting] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EICwebHosting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EICwebHosting] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EICwebHosting] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EICwebHosting] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EICwebHosting] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EICwebHosting] SET ARITHABORT OFF 
GO
ALTER DATABASE [EICwebHosting] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EICwebHosting] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EICwebHosting] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EICwebHosting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EICwebHosting] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EICwebHosting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EICwebHosting] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EICwebHosting] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EICwebHosting] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EICwebHosting] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EICwebHosting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EICwebHosting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EICwebHosting] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EICwebHosting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EICwebHosting] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EICwebHosting] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EICwebHosting] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EICwebHosting] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EICwebHosting] SET  MULTI_USER 
GO
ALTER DATABASE [EICwebHosting] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EICwebHosting] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EICwebHosting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EICwebHosting] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EICwebHosting] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EICwebHosting] SET QUERY_STORE = OFF
GO
ALTER DATABASE [EICwebHosting] SET  READ_WRITE 
GO
